name: Update version

on:
  push:
    branches:
      - "*"

jobs:
  update-patch:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm version --git-tag-version false patch
      - run: npm version --preid beta prerelease
