name: Update version

on:
  push:
    branches:
      - "*"

jobs:
  update-patch:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test
      - run: |
          PACKAGE_VERSION=$(npm version --git-tag-version false patch)
          git checkout -b $PACKAGE_VERSION
          git add package.json
          git commit -m "update package.json to $PACKAGE_VERSION"
          npm version --preid beta prerelease
          git checkout main
          git merge --squash $PACKAGE_VERSION
